tracing:
  url: http://localhost:4317

jwt:
  secret: ${JWT_SECRET:207c11ed092814462f1c6f5713f747770183a6513f8558cfbcbff824a2ba0820} # dev secret
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 2592000000

app:
  frontend:
    url: ${FRONT_URL:http://localhost:3000}
  base-url: ${BACK_URL:http://localhost:8080}


logging:
  level:
    com.teletrack: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] - %msg%n"
  include-details: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

  observations:
    key-values:
      application: ${spring.application.name}